# -*- coding: utf-8 -*-
# 该文件通过parse_cmdid.lua自动生成

XMONO_ID_CONFIG_MODEL	=	1
XMONO_ID_FUNC_TRACE_START	=	2
XMONO_ID_FUNC_TRACE_STOP	=	3
XMONO_ID_TRACE_REPORT	=	4
XMONO_ID_DISASM_METHOD_REP	=	5
XMONO_ID_DISASM_METHOD_RSP	=	6
XMONO_ID_REPLACE_METHOD_REP	=	7
XMONO_ID_REPLACE_METHOD_RSP	=	8
XMONO_ID_LIST_DOMAIN_REP	=	9
XMONO_ID_LIST_DOMAIN_RSP	=	10
XMONO_ID_STACK_TRACE_REP	=	11
XMONO_ID_STACK_TRACE_RSP	=	12
XMONO_ID_UNSTACK_TRACE_REP	=	13


